version: "3.9"
services:
    app:
        container_name: sars
        build:
            context: ./
            dockerfile: Dockerfile
        env_file: .env
        environment: 
            - PORT=8000
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        # depends_on: 
            # - mysql
            # - loader
